### ISSUE TITLE
[EPIC] Display video NFTs

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#482]
### Discussed in https://github.com/alephium/alephium-frontend/discussions/481

<div type='discussions-op-text'>

<sup>Originally posted by **VDAODAO** March 28, 2024</sup>
As of now, video NFTs are not visible in the NFT tab of the wallet. 
<img width="319" alt="Capture d’écran 2024-03-28 à 12 20 42" src="https://github.com/alephium/alephium-frontend/assets/42373571/39c20f58-8c2d-4e3f-9666-b48ea6a1033a">

<img width="300" src="https://github.com/alephium/alephium-frontend/assets/42373571/36866875-6a07-489e-b7ca-f9d1c467a5c3" />

<img width="300" src="https://github.com/alephium/alephium-frontend/assets/42373571/aa18a809-8dc6-40c7-8f14-3a1baae9d0de" />

</div>

- [ ] Display video NFTs in desktop wallet
- [ ] Display video NFTs in mobile wallet
- [ ] Display video NFTs in explorer
