### ISSUE TITLE
[EPIC] Improve explorer search functionality

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#613]
- [ ] https://github.com/alephium/alephium-frontend/issues/594
- [ ] https://github.com/alephium/alephium-frontend/issues/595
- [ ] https://github.com/alephium/alephium-frontend/issues/185
- [ ] Refactor code: https://github.com/alephium/alephium-frontend/blob/next/apps/explorer/src/components/SearchBar.tsx#L80-L107
