### ISSUE TITLE
[EPIC] Introduce continuous localization across apps

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#620]
- [x] https://github.com/alephium/alephium-frontend/issues/50
- [x] #643
- [x] #652
- [x] https://github.com/alephium/alephium-frontend/issues/562
- [x] #662
- [x] https://github.com/alephium/extension-wallet/issues/197
- [x] https://github.com/alephium/wormhole-fork/issues/131
- [x] https://github.com/alephium/wormhole-fork/issues/134
- [x] https://github.com/alephium/extension-wallet/issues/201
- [x] https://github.com/alephium/docs/issues/385

Other related issues:
- https://github.com/alephium/docs/issues/209
- https://github.com/alephium/docs/issues/330

**Comment by nop33** [comment]
1. I created an account on https://crowdin.com/ by connecting the developer@alephium.org Google account
2. I sent them an email presenting Alephium and our projects and asking if we are eligible for their free open source plan.

---

Interesting things I've read so far:
1. There is a [Crowdin GitHub Action](https://github.com/marketplace/actions/crowdin-action)
2. There is a [guide on integrating Crowdin with Docusaurus](https://docusaurus.io/docs/i18n/crowdin).

**Comment by nop33** [comment]
Last week I received an email that our application for the open source licence for the desktop wallet was accepted 🎉 

Today I worked on creating GH workflows that use the Crowdin GH action for syncing the source files and translations of the desktop wallet project to the corresponding Crowdin project. Here is my progress: #644 

---

Resources I used:
- https://crowdin.github.io/crowdin-cli/commands/crowdin
- https://github.com/marketplace/actions/crowdin-action
- https://www.youtube.com/watch?v=5b7BMuCoKGg
- https://developer.crowdin.com/configuration-file/
- https://github.com/crowdin/github-action/blob/master/EXAMPLES.md
- https://support.crowdin.com/uploading-files/
- https://store.crowdin.com/i18next-json

**Comment by nop33** [comment]
Today I created these 2 PRs to complete this task:
- https://github.com/alephium/wormhole-fork/pull/152
- https://github.com/alephium/extension-wallet/pull/232

Closing issue.
