### ISSUE TITLE
[EPIC] Code cleanup

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#623]
- [x] https://github.com/alephium/alephium-frontend/issues/134
- [ ] https://github.com/alephium/alephium-frontend/issues/227
- [ ] https://github.com/alephium/alephium-frontend/issues/75
- [ ] https://github.com/alephium/alephium-frontend/issues/70
- [ ] https://github.com/alephium/alephium-frontend/issues/581
- [ ] https://github.com/alephium/alephium-frontend/issues/320
- [ ] https://github.com/alephium/alephium-frontend/issues/75
