### ISSUE TITLE
Use Tanstack

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-frontend#712]
# Goals

- Reduce load on explorer backend (less requests)
- Improve devX by having to manage less async operations through side-effects
- Improve app performance

# Steps

- [x] 1. Replace Redux data fetching and slices with [Tanstack Query](https://tanstack.com/query/latest) for a (working) part of the codebase of the desktop wallet.
- [x] 2. Persist latest tx hash of each wallet address. When polling, query explorer backend for latest tx hash of each address. If returned hashes are different than the persisted ones, invalidate related Tanstack caches.
    - Related: https://github.com/alephium/alephium-frontend/issues/726
- [x] 3. Persist Tanstack state between app restarts. On app start, apply same methodology like polling.
    - Related: https://github.com/alephium/alephium-frontend/issues/126
- [ ] 4. Apply above steps to mobile wallet (see [2]) and extract common logic to shared package

# TODO

- [x] Install `@tanstack/eslint-plugin-query` for better linting [1]
- [ ] Install `react-native-react-query-devtools` for React Native [1]
    - Or maybe this Expo plugin `@dev-plugins/react-query`? [2]
    - Or even Reactotron plugin `reactotron-react-query`? [3]

[1]: https://tanstack.com/query/latest/docs/framework/react/devtools
[2]: https://tanstack.com/query/latest/docs/framework/react/react-native
[3]: https://github.com/hsndmr/reactotron-react-query
